### ISSUE TITLE
Many "invalid line" messages in carbon-cache listener.log

### ISSUE THREAD

**Issue by phrawzty** [joemiller/collectd-graphite#1]
Hello,

After having activated the collectd-graphite plugin I am seeing many "invalid line" messages in listender.log, for example :

<code>06/05/2011 14:02:13 :: invalid line received from client 10.1.163.11:54982, ignoring</code>

Generally speaking metrics are interpreted properly (thousands per minute, in fact), so this isn't a blocking condition; however I am curious as to which results are causing this error to appear, as I'm seeing approximately 25 to 50 per minute.

I am more than happy to investigate further - just tell me what you need. :)

**Comment by joemiller** [comment]
Thanks for the feedback.  I have not seen this one yet.

what plugins are you using with collectd?  I wonder if there are some funky metric names that are causing problems.  I am only using a few basic plugins so far (disk, cpu, interface, mem).  

Are you missing any metrics completely (such as the case might be if the metric name wasn't being formatted properly before being sent to graphite)?

What are your config settings?  in particular, buffer size

Can you run carbon-cache with --debug?  If so, does it give more indication of what the problem lines look like?

Next step, we could make a slight modification to your lib/carbon/listeners.py file and log the exact line that was received.  Should be pretty easy to add.   line 38, just add something along the lines of:

```
 log.listener("invalid line: '%s'" % line)
```

**Comment by phrawzty** [comment]
> what plugins are you using with collectd?

We're using a number from the default set, as well as some that have been built in-house - so if one of mine is the culprit, it should be easy enough to get the developer to fix it. ;)

> What are your config settings? in particular, buffer size

Nice hot bowl of copy pasta from your README.md, in fact.

> Can you run carbon-cache with --debug? If so, does it give more indication of what the problem lines look like?

Yes and no, in that order.

> Next step, we could make a slight modification [...]

Culprit found !  Our OpenBSD routers / firewalls report <code>pf</code> stats, and those metrics are the ones causing the error condition.

<pre>
06/05/2011 18:16:16 :: invalid line: 'servers.[openbsd.machine].pf.pf_limits-max states per rule.value 0 1304698573'
06/05/2011 18:16:16 :: invalid line: 'servers.[openbsd.machine].pf.pf_limits-overload table insertion.value 0 1304698573'
06/05/2011 18:16:16 :: invalid line: 'servers.[openbsd.machine].pf.pf_limits-overload flush states.value 0 1304698573'
</pre>

(Sanitised, of course.)

**Comment by joemiller** [comment]
excellent.  I think we can fix this by converting spaces into underscores.  I'll commit a patch to the master branch asap

**Comment by joemiller** [comment]
I commited a potential fix to the master branch and tagged it v2.  there's also a new tarball download available as well.

please let me know if this fixes the issue and i will close out the ticket.

thanks!

**Comment by phrawzty** [comment]
Rejoice, for the fix is good.  Thanks for looking into it !

**Comment by srini5884** [comment]
Hi Joe,

I am still having getting error  invalid line received from client 192.168.30.135:36023, ignoring in listener log, currently am using only vmstat metrics along with collectd dameon.

Even when I try to start collectd dameon, I receive below error, tried to provide a dummy comment in the error line but it didnt fix my issue.

root@ip-192-168-30-160:/var/log/carbon# sudo service collectd start
- Starting statistics collection and monitoring daemon collectd                                                                                                                     Parse error in file `/etc/collectd/collectd.conf', line 1099 near`': syntax error, unexpected $end, expecting UNQUOTED_STRING or OPENBRAC or EOL
  yyparse returned error #1
  configfile: Cannot read file `/etc/collectd/collectd.conf'.
  Unable to read config file /etc/collectd/collectd.conf.
  Error: Reading the config file failed!
  Read the syslog for details.

Thanks,
Srini
