### ISSUE TITLE
Installation/start issue collectd+perl plugin

### ISSUE THREAD

**Issue by marianogg9** [joemiller/collectd-graphite#16]
Hi Joe.
I've installed collectd 5.0.4 and perl-collectd.x86-64 5.0.4. Thin is collectd cannot load the perl plugin as said in the following error: "Starting collectd: ERROR: lt_dlopen ("/usr/lib/collectd/perl.so") failed: file not found. The most common cause for this problem are missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
Unable to load plugin perl.
ERROR: lt_dlopen ("/usr/lib/collectd/perl.so") failed: file not found. The most common cause for this problem are missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
Unable to load plugin perl."

I've moved perl.so from /lib64/collectd/ to /lib/collectd/ (as every other plugins are located there), but still won't load it.

Sorry if it's a dumb question, but I cannot figure it out.
Thanks!

**Comment by zeelot** [comment]
Any chance you found the solution to this? I'm having the same error but the `/usr/lib/collectd/perl.so` file definitely exists. Why can't it load it?

**Comment by marianogg9** [comment]
@Zeelot nothing and I gave up on this..

**Comment by joemiller** [comment]
Collectd (5.1) now comes with an official C plugin for graphite support. I would recommend using that instead.

**Comment by zeelot** [comment]
Yeah I am needing the perl plugin in order to use a RabbitMQ script. Unfortunately, it looks like there is a bug in collectd that broke the libperl detection here: https://github.com/collectd/collectd/pull/390
