### ISSUE TITLE
Flush buffer on collectd exit

### ISSUE THREAD

**Issue by wr0ngway** [joemiller/collectd-graphite#2]
Thanks for the excellent work on this plugin.  I'm noticing some gaps in my graphite graphs, and I think its due to buffering - from what I can gather from the code, if collectd restarts, the bufer just gets dropped on the floor.  Is there a way with the perl plugin to also register for exit events and flush the buffer then as well?  Perhaps just the standard perl exit handler will work?

**Comment by joemiller** [comment]
That is indeed most likely what is happening. How often do you restart collectd?   I will look into the possibility of an exit handler.

in the meantime, you could try to use a smaller buffer.  If the collectd and graphite are on the same server, there's probably not too much overhead since you're just opening/closing a tcp socket to localhost.

**Comment by joemiller** [comment]
btw, patches and pull requests are welcome!

**Comment by wr0ngway** [comment]
I usually restart as part of my deploy, so fairly frequently, but I could probably reduce that with some changes to our internal collectd plugins.
I don't know perl that well or I would have just submitted a patch, but I assume it must have exit handlers :)

I'm running collectd on about 80 machines, all feeding into graphite on its own machine.

**Comment by joemiller** [comment]
The collectd-perl docs specifically recommend against using an END {} block, but collectd's perl interface does support registering a shutdown handler (TYPE_SHUTDOWN).  However, in my testing so far, it doesn't appear that the shutdown handler is getting called.  Still investigating.

**Comment by joemiller** [comment]
ok, I've been working a little more on this, and here's where I'm at, and maybe you can help:

1) I have tried registering a TYPE_SHUTDOWN handler, but collectd never seems to call it.
2) I have tried registering a TYPE_FLUSH handler, but my collectd segfaults when you send it a USR1 signal which is supposed to trigger all flush handlers registered by any plugins.  The strange thing is, it will segfault even if I don't have a flush handler registered in our collectd-graphite perl plugin.  So the bug could be somewhere else - possibly in collectd core or in another plugin I'm running.

I'm currently working with collectd-4.10.0 on centos5, installed via rpm (collectd-4.10.0-4.el5).  What version are you working with?  Would you be will to help me test either a shutdown handler or flush handler (or both) to see what results you get?

**Comment by wr0ngway** [comment]
I'm using  4.10.1-2 on ubuntu.  Do you have your changes on a branch?  I can give it a shot...

Matt

**Comment by joemiller** [comment]
i created a new branch - flush_and_exit_handlers.  Please give this a shot.  

to test the flush handler, send a USR1 signal to your collectd process.  You should see a "graphite_flush() called" message in your collectd error log (syslog in my setup.)

the shutdown handler should output a similar message in the log if it is called properly.

**Comment by joemiller** [comment]
I recently installed a debian 6.0.1a to investigate another issue and decided to give the `flush_and_exit_handlers` branch a shot.  It seemed to work as expected.  It appears that collectd will call the flush handlers on both a SIGUSR1 and shutdown, so i will probably remove the shutdown handler.  After a little more testing I'll merge this into master and build a -3 tarball.

Did you have any success with the `flush_and_exit_handlers` branch in your testing?

**Comment by joemiller** [comment]
merged flush_and_exit_handlers branch into master after further testing (including testing with collectd 5.0) and bumped to version 3

**Comment by wr0ngway** [comment]
Sorry for the delay on responding.  Just tried the latest version on ubuntu 11.04 (collectd 4.10.1-2).
Neither a kill -USR1 nor a service restart seems to trigger the flush.  With a USR1, I do see the following in syslog, but no mention of perl/plugin

Jul 19 06:34:12 matt collectd[15749]: Flushing all data.
Jul 19 06:34:12 matt collectd[15749]: Finished flushing all data.

**Comment by wr0ngway** [comment]
Actually, even though I see no explicit record of the plugin's flush happening, there don't seem to be any gaps in my graph, so looks like it works

**Comment by joemiller** [comment]
If you pulled master within the last week or so, then you have pulled the latest code which I cut as version 3 and has the debugging print's removed from the flush function.   Glad to hear it works now, thanks for bringing this up!
