### ISSUE TITLE
plugin_load_file: The global flag is not supported, libtool 2 is required for this.

### ISSUE THREAD

**Issue by abramsm** [joemiller/collectd-graphite#8]
I'm running Centos5 with a source build of collectd 5 but I'm still running into the error related to libtool 2.  I've tried building with the options specified in the readme and I've also tried adding libpython2.4.so to my LD_PRELOAD but I still get the warning in my log files.  Can you point me in the right direction?

Sep 14 10:41:35 adq00 collectd[9132]: plugin_load_file: The global flag is not supported, libtool 2 is required for this.
Sep 14 10:41:35 adq00 collectd[9133]: Initialization complete, entering read-loop.

Thanks
Matt

**Comment by joemiller** [comment]
this module is written in perl, are you sure you didn't mean to post this to the collectd-carbon project which is a python plugin?

**Comment by joemiller** [comment]
I added a section to the README that addresses this situation, it's an issue with the collectd 4.10.3 rpm in the EPEL5 repo.  A workaround is available using LD_PRELOAD.  Please check the new version of the README for more info.
